python ../src/timeframed_graph_loader.py \
--gen_source_graphs=True \
--delta_days=30 \
--offset_days=30 \
--path='../data/reddit_dataset/linguistic/cosine/avg/bert_delta30_new/' \
--base_dataset='../data/reddit_dataset/reddit_corpus_unbalanced_filtered.gzip' \
--doc_embedding_file_path='../data/embeddings/bert/' \
--embed_type='bert' \
--merge_liwc='false' \
--dim=768 \
--embed_mode='avg' |& tee ../logs/timeframed_graph_loader_bert.txt
