python ../src/timeframed_graph_loader.py \
--gen_source_graphs=True \
--delta_days=30 \
--offset_days=30 \
--path='../data/twitter_dataset/linguistic/cosine/avg/bert_delta30/' \
--base_dataset='../data/twitter_dataset/twitter_dataset_filtered_cleaned.gzip' \
--doc_embedding_file_path='../data/twitter_dataset/bert_embeddings/' \
--embed_type='bert' \
--merge_liwc='false' \
--dim=768 \
--embed_mode='avg' |& tee ../logs/timeframed_graph_loader.txt
